### ISSUE TITLE
2022-2023年的聊天记录只显示2022年8月的

### ISSUE THREAD

**Issue by PaperPlaneDeemo** [songluyi/LoveTime#10]
感谢作者的开源，很有用，但代码可能有点兼容性问题？

**Comment by songluyi** [comment]
都快过去七八年咯，应该是默认参数的吧 默认两年吧。现在都不写代码咯，还是很怀念以前写代码的时光~

> 感谢作者的开源，很有用，但代码可能有点兼容性问题？
