### ISSUE TITLE
ZeroDivisionError: integer division or modulo by zero

### ISSUE THREAD

**Issue by dd404x** [songluyi/LoveTime#8]
![image](https://user-images.githubusercontent.com/19923974/32261032-c2421406-bf06-11e7-9daa-d6d36e883800.png)

这个问题是什么原因，哪里有问题？使用的作者的例子

**Comment by songluyi** [comment]
这个是初始化的时候问题。另外，这个项目让我很伤心，以后应该不会维护了。

**Comment by dd404x** [comment]
好吧，谢谢！
